kind: Service
apiVersion: v1
metadata:
  name: varnish-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32055
  selector:
    app: varnish-proxy
  clusterIP: 10.105.57.236
  type: NodePort
